create table if not exists public.labels (
  id bigint primary key,
  user_id uuid references auth.users(id) on delete cascade,
  name text not null,
  discogs_url text not null,
  blurb text,
  image_url text,
  notable_releases_json text not null default '[]',
  source_type text not null default 'workspace',
  active boolean not null default false,
  status text not null default 'queued',
  current_page integer not null default 1,
  total_pages integer not null default 1,
  retry_count integer not null default 0,
  last_error text,
  added_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.releases (
  id bigint primary key,
  user_id uuid references auth.users(id) on delete cascade,
  label_id bigint not null references public.labels(id) on delete cascade,
  title text not null,
  artist text not null default 'Unknown Artist',
  year integer,
  catno text,
  discogs_url text not null,
  thumb_url text,
  details_fetched boolean not null default false,
  youtube_matched boolean not null default false,
  listened boolean not null default false,
  wishlist boolean not null default false,
  match_confidence double precision not null default 0,
  processing_error text,
  fetched_at bigint not null,
  release_order integer not null default 0,
  import_source text not null default 'label'
);

create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  release_id bigint not null references public.releases(id) on delete cascade,
  position text not null,
  title text not null,
  duration text,
  artists_text text,
  listened boolean not null default false,
  saved boolean not null default false,
  wishlist boolean not null default false,
  created_at bigint not null
);

create table if not exists public.youtube_matches (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  track_id bigint not null references public.tracks(id) on delete cascade,
  video_id text not null,
  title text not null,
  channel_title text not null,
  score double precision not null default 0,
  embeddable boolean not null default true,
  chosen boolean not null default false,
  fetched_at bigint not null
);

create table if not exists public.queue_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  youtube_video_id text not null,
  track_id bigint references public.tracks(id) on delete set null,
  release_id bigint references public.releases(id) on delete set null,
  label_id bigint references public.labels(id) on delete set null,
  source text not null default 'track',
  priority integer not null default 0,
  bumped_at bigint,
  status text not null default 'pending',
  added_at bigint not null
);

create table if not exists public.feedback_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  track_id bigint references public.tracks(id) on delete set null,
  release_id bigint references public.releases(id) on delete set null,
  label_id bigint references public.labels(id) on delete set null,
  event_type text not null,
  event_value double precision not null default 1,
  source text not null default 'app',
  created_at bigint not null
);

create table if not exists public.release_signals (
  release_id bigint primary key references public.releases(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  primary_artist text,
  styles_text text not null default '',
  genres_text text not null default '',
  contributors_text text not null default '',
  companies_text text not null default '',
  format_text text not null default '',
  country text,
  year integer,
  updated_at bigint not null
);

create table if not exists public.api_cache (
  key text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  response_json text not null,
  fetched_at bigint not null,
  expires_at bigint not null
);

create table if not exists public.app_secrets (
  id bigint primary key,
  user_id uuid references auth.users(id) on delete cascade,
  discogs_token text,
  youtube_api_key text,
  updated_at bigint not null
);

create table if not exists public.__drizzle_migrations (
  id integer generated by default as identity primary key,
  hash text not null,
  created_at bigint
);

create index if not exists releases_label_id_idx on public.releases(label_id);
create index if not exists labels_user_id_idx on public.labels(user_id);
create index if not exists releases_user_id_idx on public.releases(user_id);
create index if not exists tracks_user_id_idx on public.tracks(user_id);
create index if not exists youtube_matches_user_id_idx on public.youtube_matches(user_id);
create index if not exists queue_items_user_id_idx on public.queue_items(user_id);
create index if not exists feedback_events_user_id_idx on public.feedback_events(user_id);
create index if not exists release_signals_user_id_idx on public.release_signals(user_id);
create index if not exists api_cache_user_id_idx on public.api_cache(user_id);
create index if not exists app_secrets_user_id_idx on public.app_secrets(user_id);
create index if not exists releases_release_order_idx on public.releases(release_order);
create index if not exists tracks_release_id_idx on public.tracks(release_id);
create index if not exists tracks_saved_idx on public.tracks(saved);
create index if not exists tracks_listened_idx on public.tracks(listened);
create index if not exists youtube_matches_track_id_idx on public.youtube_matches(track_id);
create index if not exists queue_items_track_id_idx on public.queue_items(track_id);
create index if not exists queue_items_status_idx on public.queue_items(status);
create index if not exists feedback_events_track_id_idx on public.feedback_events(track_id);

alter table public.labels alter column user_id set not null;
alter table public.releases alter column user_id set not null;
alter table public.tracks alter column user_id set not null;
alter table public.youtube_matches alter column user_id set not null;
alter table public.queue_items alter column user_id set not null;
alter table public.feedback_events alter column user_id set not null;
alter table public.release_signals alter column user_id set not null;
alter table public.api_cache alter column user_id set not null;
alter table public.app_secrets alter column user_id set not null;
